name = "uu-summerschool-2025"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["UuSummerschool2025"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "UuSummerschool2025"
